### ISSUE TITLE
希望可以添加计分板拖动的功能

### ISSUE THREAD

**Issue by JesKi13567** [TmallKing1/ScoreboardHelper#1]
如题，就是客户端可自定义计分板位置。

**Comment by TmallKing1** [comment]
## 简体中文
在版本 [1.1.1](https://github.com/TmallKing1/ScoreboardHelper/releases/tag/1.1.1) 中已经添加将记分板调整到左侧、左上角、左下角、右上角和右下角的功能，且可以配置记分板的Y轴偏移。

----------

## English
In version [1.1.1](https://github.com/TmallKing1/ScoreboardHelper/releases/tag/1.1.1), the function of moving the SB sidebar to the left, top left, bottom left, top right, and bottom right has been added, and the Y-axis offset of the SB sidebar can be configured.
