### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by RoonMoonlight** [TmallKing1/ScoreboardHelper#3]
1.20.6 is out and this mod does not work with 1.20.6 update. Would be grateful if this could be updated to support 1.20.6 update.

**Comment by TmallKing1** [comment]
Scoreboard Helper 1.2.0 for Minecraft 1.20.6 has been released now. Thanks for your support.

Please remind me by creating issues if there are any bugs / compatibility problems in the mod.

----

适用于 Minecraft 1.20.6 的 记分板助手 1.2.0 已经发布，感谢您的支持。

如果模组中有任何错误或兼容性问题，请创建issue以提醒我处理。
